import { pgTable, text, timestamp, boolean, integer, doublePrecision, jsonb } from "drizzle-orm/pg-core";

export const users = pgTable("users", {
  id: text("id").primaryKey(),
  email: text("email").notNull().unique(),
  passwordHash: text("password_hash").notNull(),
  fullName: text("full_name").notNull(),
  role: text("role").notNull(),
  staffRole: text("staff_role"),
  staffId: text("staff_id"),
  borrowerId: text("borrower_id"),
  phone: text("phone"),
  avatar: text("avatar"),
  isActive: boolean("is_active").default(true),
  lastLoginAt: timestamp("last_login_at"),
  createdAt: timestamp("created_at").defaultNow(),
});

export const branches = pgTable("branches", {
  id: text("id").primaryKey(),
  code: text("code").notNull(),
  name: text("name").notNull(),
  city: text("city").notNull(),
  address: text("address").notNull(),
  phone: text("phone").notNull(),
  managerName: text("manager_name").notNull(),
  managerEmail: text("manager_email").notNull(),
  activeDisbursedPool: doublePrecision("active_disbursed_pool").default(0),
  cashVaultBalance: doublePrecision("cash_vault_balance").default(0),
  activeLoansCount: integer("active_loans_count").default(0),
  color: text("color").default("#3B82F6"),
  createdAt: timestamp("created_at").defaultNow(),
});

export const staff = pgTable("staff", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  email: text("email").notNull(),
  role: text("role").notNull(),
  assignedBranchId: text("assigned_branch_id").notNull(),
  title: text("title").notNull(),
  avatar: text("avatar").notNull(),
  committee: text("committee"),
  createdAt: timestamp("created_at").defaultNow(),
});

export const loanProducts = pgTable("loan_products", {
  id: text("id").primaryKey(),
  code: text("code").notNull(),
  name: text("name").notNull(),
  category: text("category").notNull(),
  interestRate: doublePrecision("interest_rate").notNull(),
  interestType: text("interest_type").notNull(),
  minAmount: doublePrecision("min_amount").notNull(),
  maxAmount: doublePrecision("max_amount").notNull(),
  minTermMonths: integer("min_term_months").notNull(),
  maxTermMonths: integer("max_term_months").notNull(),
  repaymentFrequency: text("repayment_frequency").default("Monthly"),
  defaultRepaymentFrequency: text("default_repayment_frequency").default("Monthly"),
  processingFeePercentage: doublePrecision("processing_fee_percentage").default(2),
  latePenaltyRate: doublePrecision("late_penalty_rate").default(3),
  earlySettlementRebateRate: doublePrecision("early_settlement_rebate_rate").default(100),
  requiresCollateral: boolean("requires_collateral").default(false),
  requiresGuarantor: boolean("requires_guarantor").default(false),
  description: text("description"),
  badgeColor: text("badge_color").default("#3B82F6"),
  createdAt: timestamp("created_at").defaultNow(),
});

export const borrowers = pgTable("borrowers", {
  id: text("id").primaryKey(),
  borrowerNumber: text("borrower_number").notNull().unique(),
  fullName: text("full_name").notNull(),
  idNumber: text("id_number").notNull(),
  phone: text("phone").notNull(),
  email: text("email").notNull(),
  dateOfBirth: text("date_of_birth").notNull(),
  gender: text("gender").notNull(),
  civilStatus: text("civil_status").notNull(),
  address: text("address").notNull(),
  facebookAccount: text("facebook_account"),
  branchId: text("branch_id").notNull(),
  employmentStatus: text("employment_status").notNull(),
  employerOrBusiness: text("employer_or_business").notNull(),
  occupation: text("occupation").notNull(),
  monthlyIncome: doublePrecision("monthly_income").notNull(),
  monthlyExpenses: doublePrecision("monthly_expenses").notNull(),
  creditScore: integer("credit_score").notNull(),
  creditTier: text("credit_tier").notNull(),
  kycStatus: text("kyc_status").notNull(),
  memberStatus: text("member_status").notNull(),
  membershipDate: text("membership_date").notNull(),
  savingsBalance: doublePrecision("savings_balance").default(1000),
  shareCapital: doublePrecision("share_capital").default(15000),
  activeLoansCount: integer("active_loans_count").default(0),
  totalBorrowed: doublePrecision("total_borrowed").default(0),
  totalRepaid: doublePrecision("total_repaid").default(0),
  avatar: text("avatar").notNull(),
  joinedDate: text("joined_date").notNull(),
  lastActivityDate: text("last_activity_date").notNull(),
  notes: text("notes"),
  createdAt: timestamp("created_at").defaultNow(),
});

export const membershipApplications = pgTable("membership_applications", {
  id: text("id").primaryKey(),
  applicationNumber: text("application_number").notNull(),
  applicantName: text("applicant_name").notNull(),
  dateOfBirth: text("date_of_birth").notNull(),
  civilStatus: text("civil_status").notNull(),
  phone: text("phone").notNull(),
  email: text("email").notNull(),
  facebookAccount: text("facebook_account"),
  address: text("address").notNull(),
  occupation: text("occupation").notNull(),
  employerOrBusiness: text("employer_or_business").notNull(),
  monthlyIncome: doublePrecision("monthly_income").notNull(),
  branchId: text("branch_id").notNull(),
  submittedDate: text("submitted_date").notNull(),
  currentStep: text("current_step").notNull(),
  validIdAttached: boolean("valid_id_attached").default(true),
  proofOfIncomeAttached: boolean("proof_of_income_attached").default(true),
  twoByTwoPhotoAttached: boolean("two_by_two_photo_attached").default(true),
  membershipFeePaid: boolean("membership_fee_paid").default(false),
  initialShareCapital: doublePrecision("initial_share_capital").default(2000),
  encodedBy: text("encoded_by"),
  encodedDate: text("encoded_date"),
  backgroundInvestigation: jsonb("background_investigation"),
  bodReviewDate: text("bod_review_date"),
  bodApprovedBy: jsonb("bod_approved_by"),
  bodNotes: text("bod_notes"),
  rejectionReason: text("rejection_reason"),
  targetCompletionDate: text("target_completion_date").notNull(),
  createdBorrowerId: text("created_borrower_id"),
  createdAt: timestamp("created_at").defaultNow(),
});

export const memberUpdateRequests = pgTable("member_update_requests", {
  id: text("id").primaryKey(),
  memberId: text("member_id").notNull(),
  memberName: text("member_name").notNull(),
  memberNumber: text("member_number").notNull(),
  branchId: text("branch_id").notNull(),
  requestDate: text("request_date").notNull(),
  channel: text("channel").notNull(),
  fieldToUpdate: text("field_to_update").notNull(),
  oldValue: text("old_value").notNull(),
  newValue: text("new_value").notNull(),
  reason: text("reason").notNull(),
  supportingDocType: text("supporting_doc_type").notNull(),
  supportingDocFileName: text("supporting_doc_file_name"),
  supportingDocVerified: boolean("supporting_doc_verified").default(false),
  status: text("status").notNull().default("Pending"),
  reviewedBy: text("reviewed_by"),
  reviewDate: text("review_date"),
  remarks: text("remarks"),
  createdAt: timestamp("created_at").defaultNow(),
});

export const memberFollowUpLogs = pgTable("member_follow_up_logs", {
  id: text("id").primaryKey(),
  memberId: text("member_id").notNull(),
  memberName: text("member_name").notNull(),
  memberNumber: text("member_number").notNull(),
  branchId: text("branch_id").notNull(),
  date: text("date").notNull(),
  contactChannel: text("contact_channel").notNull(),
  conductedBy: text("conducted_by").notNull(),
  hasOutstandingLoan: boolean("has_outstanding_loan").default(false),
  outstandingLoanAmount: doublePrecision("outstanding_loan_amount").default(0),
  purpose: text("purpose").notNull(),
  memberResponse: text("member_response").notNull(),
  nextFollowUpDate: text("next_follow_up_date"),
  actionTaken: text("action_taken").notNull(),
  createdAt: timestamp("created_at").defaultNow(),
});

export const savingsAccounts = pgTable("savings_accounts", {
  id: text("id").primaryKey(),
  memberId: text("member_id").notNull(),
  memberName: text("member_name").notNull(),
  passbookNumber: text("passbook_number").notNull(),
  balance: doublePrecision("balance").default(1000),
  maintainingBalance: doublePrecision("maintaining_balance").default(1000),
  interestRate: doublePrecision("interest_rate").default(1.0),
  createdAt: timestamp("created_at").defaultNow(),
});

export const savingsTransactions = pgTable("savings_transactions", {
  id: text("id").primaryKey(),
  savingsAccountId: text("savings_account_id").notNull(),
  memberId: text("member_id").notNull(),
  memberName: text("member_name").notNull(),
  transactionNumber: text("transaction_number").notNull(),
  date: text("date").notNull(),
  type: text("type").notNull(),
  amount: doublePrecision("amount").notNull(),
  balanceBefore: doublePrecision("balance_before").notNull(),
  balanceAfter: doublePrecision("balance_after").notNull(),
  processedBy: text("processed_by").notNull(),
  notes: text("notes"),
  officialReceiptNumber: text("official_receipt_number"),
  createdAt: timestamp("created_at").defaultNow(),
});

export const savingsWithdrawalRequests = pgTable("savings_withdrawal_requests", {
  id: text("id").primaryKey(),
  requestId: text("request_id").notNull(),
  memberId: text("member_id").notNull(),
  memberName: text("member_name").notNull(),
  branchId: text("branch_id").notNull(),
  currentBalance: doublePrecision("current_balance").notNull(),
  requestedAmount: doublePrecision("requested_amount").notNull(),
  maintainingBalance: doublePrecision("maintaining_balance").default(1000),
  remainingBalanceAfter: doublePrecision("remaining_balance_after").notNull(),
  requestDate: text("request_date").notNull(),
  reason: text("reason").notNull(),
  tellerName: text("teller_name").notNull(),
  tellerRecordedDate: text("teller_recorded_date").notNull(),
  status: text("status").notNull().default("Pending Approval"),
  approvedByManager: text("approved_by_manager"),
  approvalDate: text("approval_date"),
  disbursedDate: text("disbursed_date"),
  rejectionReason: text("rejection_reason"),
  createdAt: timestamp("created_at").defaultNow(),
});

export const interestCreditLogs = pgTable("interest_credit_logs", {
  id: text("id").primaryKey(),
  periodMonth: text("period_month").notNull(),
  calculationDate: text("calculation_date").notNull(),
  annualRate: doublePrecision("annual_rate").default(1.0),
  totalMembersCredited: integer("total_members_credited").notNull(),
  totalInterestDistributed: doublePrecision("total_interest_distributed").notNull(),
  executedBy: text("executed_by").notNull(),
  createdAt: timestamp("created_at").defaultNow(),
});

export const loans = pgTable("loans", {
  id: text("id").primaryKey(),
  loanNumber: text("loan_number").notNull().unique(),
  borrowerId: text("borrower_id").notNull(),
  borrowerName: text("borrower_name").notNull(),
  borrowerPhone: text("borrower_phone").notNull(),
  borrowerAvatar: text("borrower_avatar"),
  branchId: text("branch_id").notNull(),
  productId: text("product_id").notNull(),
  productName: text("product_name").notNull(),
  principalAmount: doublePrecision("principal_amount").notNull(),
  interestRate: doublePrecision("interest_rate").notNull(),
  interestType: text("interest_type").notNull(),
  repaymentFrequency: text("repayment_frequency").notNull(),
  termMonths: integer("term_months").notNull(),
  totalInstallments: integer("total_installments").notNull(),
  processingFee: doublePrecision("processing_fee").notNull(),
  totalInterest: doublePrecision("total_interest").notNull(),
  totalPayable: doublePrecision("total_payable").notNull(),
  totalPaid: doublePrecision("total_paid").default(0),
  remainingBalance: doublePrecision("remaining_balance").notNull(),
  status: text("status").notNull(),
  coopStep: text("coop_step").notNull(),
  applicationDate: text("application_date").notNull(),
  startDate: text("start_date"),
  approvalDate: text("approval_date"),
  disbursedDate: text("disbursed_date"),
  nextPaymentDate: text("next_payment_date"),
  maturityDate: text("maturity_date").notNull(),
  loanOfficerId: text("loan_officer_id").notNull(),
  loanOfficerName: text("loan_officer_name").notNull(),
  purpose: text("purpose").notNull(),
  collateral: jsonb("collateral"),
  guarantors: jsonb("guarantors"),
  schedule: jsonb("schedule"),
  underwritingReport: jsonb("underwriting_report"),
  creditCommitteeEval: jsonb("credit_committee_eval"),
  disbursementVoucher: jsonb("disbursement_voucher"),
  lastPaymentDate: text("last_payment_date"),
  daysInArrears: integer("days_in_arrears").default(0),
  isIrregularAccount: boolean("is_irregular_account").default(false),
  totalLatePenaltiesCharged: doublePrecision("total_late_penalties_charged").default(0),
  totalRebatesAwarded: doublePrecision("total_rebates_awarded").default(0),
  disbursementMethod: text("disbursement_method"),
  disbursementAccount: text("disbursement_account"),
  officerInCharge: text("officer_in_charge"),
  createdAt: timestamp("created_at").defaultNow(),
});

export const payments = pgTable("payments", {
  id: text("id").primaryKey(),
  receiptNumber: text("receipt_number").notNull().unique(),
  loanId: text("loan_id").notNull(),
  loanNumber: text("loan_number").notNull(),
  borrowerId: text("borrower_id").notNull(),
  borrowerName: text("borrower_name").notNull(),
  branchId: text("branch_id").notNull(),
  amount: doublePrecision("amount").notNull(),
  paymentDate: text("payment_date").notNull(),
  paymentMethod: text("payment_method").notNull(),
  transactionReference: text("transaction_reference").notNull(),
  collectedBy: text("collected_by").notNull(),
  principalPortion: doublePrecision("principal_portion").notNull(),
  interestPortion: doublePrecision("interest_portion").notNull(),
  penaltyPortion: doublePrecision("penalty_portion").default(0),
  rebateDiscount: doublePrecision("rebate_discount").default(0),
  paymentScheduleType: text("payment_schedule_type").notNull(),
  isAdvancePayment: boolean("is_advance_payment").default(false),
  notes: text("notes"),
  createdAt: timestamp("created_at").defaultNow(),
});

export const auditLogs = pgTable("audit_logs", {
  id: text("id").primaryKey(),
  timestamp: text("timestamp").notNull(),
  action: text("action").notNull(),
  details: text("details").notNull(),
  performedBy: text("performed_by").notNull(),
  branchId: text("branch_id").notNull(),
  type: text("type").notNull(),
  userName: text("user_name"),
  userRole: text("user_role"),
  targetType: text("target_type"),
  targetId: text("target_id"),
  ipAddress: text("ip_address"),
  createdAt: timestamp("created_at").defaultNow(),
});

export const solidarityGroups = pgTable("solidarity_groups", {
  id: text("id").primaryKey(),
  groupCode: text("group_code").notNull().unique(),
  groupName: text("group_name").notNull(),
  centerName: text("center_name").notNull(),
  branchId: text("branch_id").notNull(),
  formedDate: text("formed_date").notNull(),
  meetingDay: text("meeting_day").notNull(),
  meetingTime: text("meeting_time").notNull(),
  meetingLocation: text("meeting_location").notNull(),
  loanOfficerId: text("loan_officer_id").notNull(),
  loanOfficerName: text("loan_officer_name").notNull(),
  leaderBorrowerId: text("leader_borrower_id").notNull(),
  leaderName: text("leader_name").notNull(),
  leaderPhone: text("leader_phone").notNull(),
  members: jsonb("members").notNull(),
  totalActiveLoans: doublePrecision("total_active_loans").default(0),
  totalGroupSavings: doublePrecision("total_group_savings").default(0),
  repaymentRate: doublePrecision("repayment_rate").default(100),
  solidarityFundBalance: doublePrecision("solidarity_fund_balance").default(0),
  jointLiabilityAgreed: boolean("joint_liability_agreed").default(true),
  status: text("status").notNull().default("Active"),
  createdAt: timestamp("created_at").defaultNow(),
});

