import {
  BranchContextData,
  BranchDashboard,
  BranchLoan,
  BranchLoanDetail,
  BranchPayment,
  BranchPersonnel,
  BranchSavingsAccount,
  ClientDetail,
  FinancialTransactionRow,
  LoanAssessment,
  LoanProduct,
  PerformanceData,
  ReportRow,
  SolidarityGroup,
  TodayCollections,
} from '../types';

const today = new Date().toISOString().slice(0, 10);
const iso = new Date().toISOString();

const personnel: BranchPersonnel = {
  staffId: 'staff-off1',
  name: 'Maria Santos',
  email: 'maria.santos@losbanos.coop',
  role: 'LOAN_OFFICER',
  title: 'Senior Loan Officer',
  avatar: '',
  accountStatus: 'Active',
};

export const mockBranchContext: BranchContextData = {
  personnel,
  branch: {
    id: 'br-main',
    name: 'Los Baños Main Branch',
    code: 'LB-MAIN',
    address: '122 Grove St, Los Baños, Laguna',
    branchManager: 'Carla Reyes',
    contactPhone: '0917 000 1234',
    status: 'Active',
  },
  permissions: [
    'register_clients',
    'manage_kyc',
    'view_client_info',
    'assist_clients',
    'process_loan_applications',
    'review_client_loan_info',
    'manage_loan_applications',
    'monitor_loan_repayment',
    'view_transaction_records',
  ],
  viewAll: false,
};

const baseClients: ClientDetail[] = [
  {
    id: 'bor-1001',
    borrowerNumber: 'CLI-2024-0123',
    fullName: 'Juan Dela Cruz',
    idNumber: 'ID-8821-221',
    phone: '0917 555 1201',
    email: 'juan.dc@example.com',
    dateOfBirth: '1988-05-12',
    gender: 'Male',
    civilStatus: 'Married',
    address: 'Blk 4 Lot 7, Brgy. Bambang, Los Baños, Laguna',
    facebookAccount: 'juan.dc',
    branchId: 'br-main',
    employmentStatus: 'Employed',
    employerOrBusiness: 'Green Valley Farms',
    occupation: 'Farm Worker',
    monthlyIncome: 18000,
    monthlyExpenses: 9500,
    creditScore: 640,
    creditTier: 'Standard',
    kycStatus: 'Verified',
    memberStatus: 'Active',
    membershipDate: '2023-02-14',
    savingsBalance: 8500,
    shareCapital: 15000,
    activeLoansCount: 2,
    totalBorrowed: 90000,
    totalRepaid: 46000,
    avatar: '',
    joinedDate: '2023-02-14',
    lastActivityDate: today,
    notes: null,
  },
  {
    id: 'bor-1002',
    borrowerNumber: 'CLI-2024-0456',
    fullName: 'Ana Marie Reyes',
    idNumber: 'ID-6710-892',
    phone: '0918 555 2093',
    email: 'ana.reyes@example.com',
    dateOfBirth: '1991-11-03',
    gender: 'Female',
    civilStatus: 'Single',
    address: 'Unit 22, Maharlika St., Brgy. Batong Malake',
    facebookAccount: 'ana.rm',
    branchId: 'br-main',
    employmentStatus: 'Self-Employed',
    employerOrBusiness: 'Ana\'s Sari-Sari Store',
    occupation: 'Store Owner',
    monthlyIncome: 15000,
    monthlyExpenses: 8000,
    creditScore: 620,
    creditTier: 'Standard',
    kycStatus: 'Pending Review',
    memberStatus: 'Pending',
    membershipDate: '2024-01-20',
    savingsBalance: 2500,
    shareCapital: 2000,
    activeLoansCount: 0,
    totalBorrowed: 0,
    totalRepaid: 0,
    avatar: '',
    joinedDate: '2024-01-20',
    lastActivityDate: today,
    notes: 'Awaiting valid ID submission.',
  },
  {
    id: 'bor-1003',
    borrowerNumber: 'CLI-2024-0789',
    fullName: 'Ramon Bautista',
    idNumber: 'ID-4412-778',
    phone: '0920 555 7712',
    email: 'ramon.bautista@example.com',
    dateOfBirth: '1979-07-21',
    gender: 'Male',
    civilStatus: 'Married',
    address: '17 Silang St., Brgy. Anos',
    facebookAccount: 'rbautista',
    branchId: 'br-main',
    employmentStatus: 'Employed',
    employerOrBusiness: 'Lakambini Transport Coop',
    occupation: 'Utility Driver',
    monthlyIncome: 21000,
    monthlyExpenses: 12000,
    creditScore: 660,
    creditTier: 'Good',
    kycStatus: 'Verified',
    memberStatus: 'Active',
    membershipDate: '2022-08-01',
    savingsBalance: 12400,
    shareCapital: 18000,
    activeLoansCount: 1,
    totalBorrowed: 60000,
    totalRepaid: 28500,
    avatar: '',
    joinedDate: '2022-08-01',
    lastActivityDate: today,
    notes: null,
  },
  {
    id: 'bor-1004',
    borrowerNumber: 'CLI-2024-0345',
    fullName: 'Liza Fernandez',
    idNumber: 'ID-3309-104',
    phone: '0919 555 3304',
    email: 'liza.fernandez@example.com',
    dateOfBirth: '1995-03-28',
    gender: 'Female',
    civilStatus: 'Single',
    address: 'Brgy. San Antonio, Bay, Laguna',
    facebookAccount: 'liza.f',
    branchId: 'br-main',
    employmentStatus: 'Self-Employed',
    employerOrBusiness: 'Liza\'s Bakeshop',
    occupation: 'Bakeshop Owner',
    monthlyIncome: 26000,
    monthlyExpenses: 14000,
    creditScore: 700,
    creditTier: 'Preferred',
    kycStatus: 'Verified',
    memberStatus: 'Active',
    membershipDate: '2023-06-10',
    savingsBalance: 22100,
    shareCapital: 20000,
    activeLoansCount: 1,
    totalBorrowed: 120000,
    totalRepaid: 62000,
    avatar: '',
    joinedDate: '2023-06-10',
    lastActivityDate: today,
    notes: null,
  },
  {
    id: 'bor-1005',
    borrowerNumber: 'CLI-2024-0912',
    fullName: 'Pedro Salvador',
    idNumber: 'ID-5543-119',
    phone: '0915 555 8845',
    email: 'pedro.salvador@example.com',
    dateOfBirth: '1985-09-17',
    gender: 'Male',
    civilStatus: 'Widowed',
    address: 'Brgy. Mayondon, Los Baños',
    facebookAccount: null,
    branchId: 'br-main',
    employmentStatus: 'Employed',
    employerOrBusiness: 'UP Los Baños',
    occupation: 'Groundskeeper',
    monthlyIncome: 19000,
    monthlyExpenses: 10500,
    creditScore: 610,
    creditTier: 'Standard',
    kycStatus: 'Correction Requested',
    memberStatus: 'Active',
    membershipDate: '2023-10-05',
    savingsBalance: 4100,
    shareCapital: 15000,
    activeLoansCount: 1,
    totalBorrowed: 45000,
    totalRepaid: 21000,
    avatar: '',
    joinedDate: '2023-10-05',
    lastActivityDate: today,
    notes: 'Proof of income needs re-upload.',
  },
];

function scheduleFor(principal: number, monthly: number, months: number) {
  let balance = principal;
  const now = new Date();
  return Array.from({ length: months }, (_, i) => {
    const due = new Date(now.getFullYear(), now.getMonth() + i + 1, 15);
    const principalPortion = Math.min(Math.round(balance * 100) / 100, monthly);
    const isPaid = i < Math.floor(months * 0.4);
    balance = Math.max(0, Math.round((balance - principalPortion) * 100) / 100);
    return {
      installmentNumber: i + 1,
      dueDate: due.toISOString().slice(0, 10),
      principal: Math.round(principalPortion * 100) / 100,
      interest: Math.round(monthly * 0.2 * 100) / 100,
      fees: 100,
      totalDue: Math.round(monthly * 100) / 100,
      amountPaid: isPaid ? Math.round(monthly * 100) / 100 : 0,
      remainingBalance: balance,
      status: isPaid ? 'Paid' : i === Math.floor(months * 0.4) ? 'Due' : 'Upcoming',
      paidDate: isPaid ? undefined : undefined,
    };
  });
}

const baseLoans: BranchLoan[] = [
  {
    id: 'loan-2001',
    loanNumber: 'LA-2024-1187',
    borrowerId: 'bor-1001',
    borrowerName: 'Juan Dela Cruz',
    branchId: 'br-main',
    productName: 'Agri Loan',
    principalAmount: 40000,
    interestRate: 12,
    interestType: 'Flat Rate',
    repaymentFrequency: 'Monthly',
    termMonths: 12,
    totalInstallments: 12,
    processingFee: 800,
    totalInterest: 14400,
    totalPayable: 55200,
    totalPaid: 23000,
    remainingBalance: 32200,
    status: 'Active',
    applicationDate: '2023-03-01',
    startDate: '2023-03-15',
    maturityDate: '2024-03-15',
    nextPaymentDate: '2024-02-15',
    loanOfficerName: 'Maria Santos',
    purpose: 'Planting season capital for rice farm',
    daysInArrears: 0,
    schedule: scheduleFor(55200, 4600, 12),
  },
  {
    id: 'loan-2002',
    loanNumber: 'LA-2024-2206',
    borrowerId: 'bor-1001',
    borrowerName: 'Juan Dela Cruz',
    branchId: 'br-main',
    productName: 'Micro Enterprise Loan',
    principalAmount: 50000,
    interestRate: 14,
    interestType: 'Flat Rate',
    repaymentFrequency: 'Monthly',
    termMonths: 18,
    totalInstallments: 18,
    processingFee: 1000,
    totalInterest: 21000,
    totalPayable: 72000,
    totalPaid: 12000,
    remainingBalance: 60000,
    status: 'Active',
    applicationDate: '2023-09-10',
    startDate: '2023-09-20',
    maturityDate: '2025-03-20',
    nextPaymentDate: '2024-02-20',
    loanOfficerName: 'Maria Santos',
    purpose: 'Capital for farm supply retail',
    daysInArrears: 0,
    schedule: scheduleFor(72000, 4000, 18),
  },
  {
    id: 'loan-2003',
    loanNumber: 'LA-2024-0911',
    borrowerId: 'bor-1003',
    borrowerName: 'Ramon Bautista',
    branchId: 'br-main',
    productName: 'Salary Loan',
    principalAmount: 25000,
    interestRate: 10,
    interestType: 'Flat Rate',
    repaymentFrequency: 'Monthly',
    termMonths: 10,
    totalInstallments: 10,
    processingFee: 500,
    totalInterest: 7500,
    totalPayable: 33000,
    totalPaid: 6600,
    remainingBalance: 26400,
    status: 'In Arrears',
    applicationDate: '2023-07-01',
    startDate: '2023-07-12',
    maturityDate: '2024-05-12',
    nextPaymentDate: '2023-12-12',
    loanOfficerName: 'Maria Santos',
    purpose: 'Emergency expenses',
    daysInArrears: 34,
    schedule: scheduleFor(33000, 3300, 10),
  },
  {
    id: 'loan-2004',
    loanNumber: 'LA-2024-3308',
    borrowerId: 'bor-1004',
    borrowerName: 'Liza Fernandez',
    branchId: 'br-main',
    productName: 'Women\'s Livelihood Loan',
    principalAmount: 80000,
    interestRate: 12,
    interestType: 'Flat Rate',
    repaymentFrequency: 'Monthly',
    termMonths: 24,
    totalInstallments: 24,
    processingFee: 1600,
    totalInterest: 38400,
    totalPayable: 120000,
    totalPaid: 40000,
    remainingBalance: 80000,
    status: 'Disbursed',
    applicationDate: '2023-11-01',
    startDate: '2023-11-10',
    maturityDate: '2025-11-10',
    nextPaymentDate: '2024-02-10',
    loanOfficerName: 'Maria Santos',
    purpose: 'Bakeshop equipment upgrade',
    daysInArrears: 0,
    schedule: scheduleFor(120000, 5000, 24),
  },
  {
    id: 'loan-2005',
    loanNumber: 'LA-2024-4099',
    borrowerId: 'bor-1005',
    borrowerName: 'Pedro Salvador',
    branchId: 'br-main',
    productName: 'Education Loan',
    principalAmount: 20000,
    interestRate: 8,
    interestType: 'Flat Rate',
    repaymentFrequency: 'Monthly',
    termMonths: 8,
    totalInstallments: 8,
    processingFee: 400,
    totalInterest: 4800,
    totalPayable: 25200,
    totalPaid: 6300,
    remainingBalance: 18900,
    status: 'Active',
    applicationDate: '2023-12-05',
    startDate: '2023-12-15',
    maturityDate: '2024-08-15',
    nextPaymentDate: '2024-02-15',
    loanOfficerName: 'Maria Santos',
    purpose: 'School fees for dependents',
    daysInArrears: 0,
    schedule: scheduleFor(25200, 3150, 8),
  },
  {
    id: 'loan-2006',
    loanNumber: 'LA-2024-5567',
    borrowerId: 'bor-1002',
    borrowerName: 'Ana Marie Reyes',
    branchId: 'br-main',
    productName: 'Micro Enterprise Loan',
    principalAmount: 30000,
    interestRate: 14,
    interestType: 'Flat Rate',
    repaymentFrequency: 'Monthly',
    termMonths: 12,
    totalInstallments: 12,
    processingFee: 600,
    totalInterest: 12600,
    totalPayable: 43200,
    totalPaid: 0,
    remainingBalance: 43200,
    status: 'For Assessment',
    applicationDate: '2024-01-18',
    loanOfficerName: 'Maria Santos',
    purpose: 'Inventory for sari-sari store',
    schedule: scheduleFor(43200, 3600, 12),
  },
];

const basePayments: BranchPayment[] = [
  {
    id: 'pay-3001',
    receiptNumber: 'OR-2024-881234',
    loanId: 'loan-2001',
    loanNumber: 'LA-2024-1187',
    borrowerId: 'bor-1001',
    borrowerName: 'Juan Dela Cruz',
    branchId: 'br-main',
    amount: 4600,
    paymentDate: today,
    paymentMethod: 'Cash',
    collectedBy: 'Maria Santos',
    principalPortion: 3400,
    interestPortion: 1200,
  },
  {
    id: 'pay-3002',
    receiptNumber: 'OR-2024-881235',
    loanId: 'loan-2004',
    loanNumber: 'LA-2024-3308',
    borrowerId: 'bor-1004',
    borrowerName: 'Liza Fernandez',
    branchId: 'br-main',
    amount: 5000,
    paymentDate: today,
    paymentMethod: 'GCash',
    collectedBy: 'Maria Santos',
    principalPortion: 3800,
    interestPortion: 1200,
  },
  {
    id: 'pay-3003',
    receiptNumber: 'OR-2024-881101',
    loanId: 'loan-2001',
    loanNumber: 'LA-2024-1187',
    borrowerId: 'bor-1001',
    borrowerName: 'Juan Dela Cruz',
    branchId: 'br-main',
    amount: 4600,
    paymentDate: '2024-01-15',
    paymentMethod: 'Cash',
    collectedBy: 'Maria Santos',
    principalPortion: 3400,
    interestPortion: 1200,
  },
];

const savingsAccounts: BranchSavingsAccount[] = [
  { id: 'sav-5001', memberId: 'bor-1001', memberName: 'Juan Dela Cruz', balance: 8500, totalDeposits: 36000, totalWithdrawals: 27500, maintainingBalance: 1000 },
  { id: 'sav-5002', memberId: 'bor-1004', memberName: 'Liza Fernandez', balance: 22100, totalDeposits: 42000, totalWithdrawals: 19900, maintainingBalance: 1000 },
  { id: 'sav-5003', memberId: 'bor-1003', memberName: 'Ramon Bautista', balance: 12400, totalDeposits: 30000, totalWithdrawals: 17600, maintainingBalance: 1000 },
  { id: 'sav-5004', memberId: 'bor-1005', memberName: 'Pedro Salvador', balance: 4100, totalDeposits: 15000, totalWithdrawals: 10900, maintainingBalance: 1000 },
  { id: 'sav-5005', memberId: 'bor-1002', memberName: 'Ana Marie Reyes', balance: 2500, totalDeposits: 4000, totalWithdrawals: 1500, maintainingBalance: 1000 },
];

const groups: SolidarityGroup[] = [
  {
    id: 'grp-7001',
    groupCode: 'SG-2023-0101',
    groupName: 'Bambang Farmers',
    centerName: 'Center 1',
    branchId: 'br-main',
    formedDate: '2023-04-02',
    meetingDay: 'Saturday',
    meetingTime: '9:00 AM',
    meetingLocation: 'Brgy. Bambang Hall',
    loanOfficerName: 'Maria Santos',
    leaderBorrowerId: 'bor-1001',
    leaderName: 'Juan Dela Cruz',
    leaderPhone: '0917 555 1201',
    members: [
      { borrowerId: 'bor-1001', fullName: 'Juan Dela Cruz', phone: '0917 555 1201', role: 'Leader', status: 'Good Standing', weeklyDues: 200 },
      { borrowerId: 'bor-1004', fullName: 'Liza Fernandez', phone: '0919 555 3304', role: 'Member', status: 'Good Standing', weeklyDues: 200 },
      { borrowerId: 'bor-1003', fullName: 'Ramon Bautista', phone: '0920 555 7712', role: 'Member', status: 'Arrears', weeklyDues: 200 },
    ],
    totalActiveLoans: 3,
    totalGroupSavings: 13000,
    repaymentRate: 96,
    solidarityFundBalance: 1800,
    status: 'Active',
  },
];

const transactions: FinancialTransactionRow[] = [
  {
    id: 'txn-9001',
    referenceNumber: 'TX-OR-2024-881234',
    clientId: 'bor-1001',
    clientName: 'Juan Dela Cruz',
    accountOrLoanId: 'loan-2001',
    accountOrLoanType: 'Loan',
    branchId: 'br-main',
    transactionType: 'Loan Repayment',
    amount: 4600,
    transactionDate: today,
    paymentMethod: 'Cash',
    processedBy: 'Maria Santos (Loan Officer)',
    processedByRole: 'LOAN_OFFICER',
    status: 'Completed',
    notes: `Collection for LA-2024-1187 · OR-2024-881234`,
  },
  {
    id: 'txn-9002',
    referenceNumber: 'TX-OR-2024-881235',
    clientId: 'bor-1004',
    clientName: 'Liza Fernandez',
    accountOrLoanId: 'loan-2004',
    accountOrLoanType: 'Loan',
    branchId: 'br-main',
    transactionType: 'Loan Repayment',
    amount: 5000,
    transactionDate: today,
    paymentMethod: 'GCash',
    processedBy: 'Maria Santos (Loan Officer)',
    processedByRole: 'LOAN_OFFICER',
    status: 'Completed',
    notes: `Collection for LA-2024-3308 · OR-2024-881235`,
  },
  {
    id: 'txn-9003',
    referenceNumber: 'TX-REF-2024-00991',
    clientId: 'bor-1004',
    clientName: 'Liza Fernandez',
    accountOrLoanId: 'sav-5002',
    accountOrLoanType: 'Savings',
    branchId: 'br-main',
    transactionType: 'Savings Deposit',
    amount: 2000,
    transactionDate: today,
    paymentMethod: 'Cash',
    processedBy: 'Maria Santos (Loan Officer)',
    processedByRole: 'LOAN_OFFICER',
    status: 'Completed',
    notes: null,
  },
];

export const mockTodayCollections: TodayCollections = {
  payments: basePayments.filter((p) => p.paymentDate === today),
  totals: {
    total: basePayments.filter((p) => p.paymentDate === today).reduce((s, p) => s + p.amount, 0),
    count: basePayments.filter((p) => p.paymentDate === today).length,
    cash: basePayments.filter((p) => p.paymentDate === today && p.paymentMethod === 'Cash').reduce((s, p) => s + p.amount, 0),
    other: basePayments.filter((p) => p.paymentDate === today && p.paymentMethod !== 'Cash').reduce((s, p) => s + p.amount, 0),
  },
};

export const mockDashboard: BranchDashboard = {
  asOf: iso,
  summary: {
    totalClients: baseClients.length,
    activeClients: baseClients.filter((c) => c.memberStatus === 'Active').length,
    pendingVerification: baseClients.filter((c) => c.kycStatus !== 'Verified' || c.memberStatus === 'Pending').length,
    activeLoans: baseLoans.filter((l) => ['Disbursed', 'Active', 'In Arrears'].includes(l.status)).length,
    outstandingBalance: baseLoans.reduce((s, l) => s + l.remainingBalance, 0),
    todayCollections: mockTodayCollections.totals.total,
    todayTransactionCount: mockTodayCollections.totals.count,
    pendingApplications: baseLoans.filter((l) => ['Draft', 'Submitted', 'Under Review', 'For Assessment'].includes(l.status)).length,
    totalSavings: savingsAccounts.reduce((s, a) => s + a.balance, 0),
    todayDeposits: 2000,
    todayWithdrawals: 0,
    overdueLoans: baseLoans.filter((l) => l.status === 'In Arrears' || (l.daysInArrears && l.daysInArrears > 0)).length,
    overdueOutstanding: baseLoans.filter((l) => l.status === 'In Arrears').reduce((s, l) => s + l.remainingBalance, 0),
  },
};

export const mockPerformance: PerformanceData = {
  range: 'month',
  portfolio: { active: 5, completed: 3, overdue: 1, pending: 1 },
  collections: {
    daily: [
      ['2024-01-02', 4500],
      ['2024-01-05', 8200],
      ['2024-01-09', 4100],
      ['2024-01-12', 9200],
      ['2024-01-16', 7400],
      ['2024-01-19', 11300],
      ['2024-01-23', 6800],
      ['2024-01-26', 9700],
      ['2024-01-30', 5100],
      ['2024-02-02', 12400],
    ],
    weekly: [
      ['2024-01-01', 12700],
      ['2024-01-08', 13300],
      ['2024-01-15', 22100],
      ['2024-01-22', 16500],
      ['2024-01-29', 17500],
    ],
    monthly: [
      ['2023-09', 118000],
      ['2023-10', 124500],
      ['2023-11', 132200],
      ['2023-12', 147800],
      ['2024-01', 139400],
      ['2024-02', 42100],
    ],
    total: 139400,
  },
  clientGrowth: { newClients: 3, active: 4, inactive: 0, monthly: [['2023-09', 1], ['2023-11', 1], ['2024-01', 1]] },
  savings: { deposits: 22600, withdrawals: 9800, net: 12800 },
};

export const mockClients = baseClients;

export function mockClientsFiltered(query: string): ClientDetail[] {
  const q = query.toLowerCase();
  if (!q) return baseClients;
  return baseClients.filter(
    (c) =>
      c.fullName.toLowerCase().includes(q) ||
      c.borrowerNumber.toLowerCase().includes(q) ||
      c.phone.includes(q)
  );
}

export const mockKycQueue = baseClients.filter(
  (c) => !['verified', 'rejected'].includes(c.kycStatus.toLowerCase()) || c.memberStatus.toLowerCase() === 'pending'
).map((c) => ({ ...c, submittedDocuments: c.id === 'bor-1002' ? 1 : 2 }));

export const mockLoanProducts: LoanProduct[] = [
  { id: 'prod-1', name: 'Agri Loan', code: 'AGRI', minAmount: 10000, maxAmount: 150000, minTermMonths: 6, maxTermMonths: 24, interestRatePerMonth: 1, interestType: 'Flat Rate', processingFeePercentage: 2, description: 'Short-term capital for agricultural production and farming inputs.' },
  { id: 'prod-2', name: 'Micro Enterprise Loan', code: 'MICRO', minAmount: 10000, maxAmount: 200000, minTermMonths: 6, maxTermMonths: 36, interestRatePerMonth: 1.17, interestType: 'Flat Rate', processingFeePercentage: 2, description: 'Working capital for micro and small enterprises and sari-sari stores.' },
  { id: 'prod-3', name: 'Salary Loan', code: 'SALARY', minAmount: 5000, maxAmount: 100000, minTermMonths: 3, maxTermMonths: 18, interestRatePerMonth: 0.83, interestType: 'Flat Rate', processingFeePercentage: 2, description: 'Fast cash assistance for salaried members with stable income.' },
  { id: 'prod-4', name: 'Education Loan', code: 'EDU', minAmount: 5000, maxAmount: 80000, minTermMonths: 3, maxTermMonths: 24, interestRatePerMonth: 0.67, interestType: 'Flat Rate', processingFeePercentage: 2, description: 'Tuition and school expenses for dependents of active members.' },
  { id: 'prod-5', name: 'Women\'s Livelihood Loan', code: 'WLL', minAmount: 10000, maxAmount: 200000, minTermMonths: 6, maxTermMonths: 36, interestRatePerMonth: 1, interestType: 'Flat Rate', processingFeePercentage: 2, description: 'Livelihood and income-generating projects led by women members.' },
];

export const mockLoanApplications: BranchLoan[] = baseLoans.filter((l) =>
  ['Draft', 'Submitted', 'Under Review', 'For Assessment'].includes(l.status)
);

export const mockLoans = baseLoans;

export function mockLoanDetail(loanId: string): BranchLoanDetail {
  const loan = baseLoans.find((l) => l.id === loanId) || baseLoans[0];
  const client = baseClients.find((c) => c.id === loan.borrowerId) || baseClients[0];
  const payments = basePayments.filter((p) => p.loanId === loan.id);
  const amortization = (loan.schedule || []).map((s) => ({ ...s }));
  return { loan, amortization, payments, borrower: client };
}

export const mockSavingsAccounts = savingsAccounts;

export const mockGroups = groups;

export function mockGroupDetail(id: string) {
  const group = groups.find((g) => g.id === id) || groups[0];
  const members = group.members.map((m) => {
    const memberLoans = baseLoans.filter((l) => l.borrowerId === m.borrowerId);
    const outstanding = memberLoans.reduce((s, l) => s + (l.remainingBalance || 0), 0);
    return {
      ...m,
      activeLoans: memberLoans.length,
      outstandingBalance: Math.round(outstanding * 100) / 100,
      repaymentStatus: m.status === 'Arrears' ? 'Arrears' : outstanding > 0 ? 'Good Standing' : 'Good Standing',
    };
  });
  return { group, members };
}

export const mockTransactions = transactions;

export const mockDocuments = [
  {
    id: 'doc-8001',
    docNumber: 'DOC-2024-119001',
    branchId: 'br-main',
    clientId: 'bor-1002',
    clientName: 'Ana Marie Reyes',
    loanId: null,
    loanNumber: null,
    docName: 'Valid ID (UMID)',
    docType: 'ID Document',
    fileUrl: null,
    uploadedBy: 'Maria Santos',
    status: 'Active',
    notes: 'Front and back copy.',
    createdAt: iso,
  },
  {
    id: 'doc-8002',
    docNumber: 'DOC-2024-119002',
    branchId: 'br-main',
    clientId: 'bor-1001',
    clientName: 'Juan Dela Cruz',
    loanId: 'loan-2002',
    loanNumber: 'LA-2024-2206',
    docName: 'Collateral Deed of Assignment',
    docType: 'Collateral Document',
    fileUrl: null,
    uploadedBy: 'Maria Santos',
    status: 'Active',
    notes: null,
    createdAt: iso,
  },
  {
    id: 'doc-8003',
    docNumber: 'DOC-2024-119003',
    branchId: 'br-main',
    clientId: 'bor-1005',
    clientName: 'Pedro Salvador',
    loanId: null,
    loanNumber: null,
    docName: 'Proof of Income (Payslip)',
    docType: 'Proof of Income',
    fileUrl: null,
    uploadedBy: 'Maria Santos',
    status: 'Active',
    notes: 'Latest 3 months payslips.',
    createdAt: iso,
  },
];

export const mockNotifications = [
  {
    id: 'ntf-6001',
    branchId: 'br-main',
    targetStaffId: null,
    type: 'KYC',
    title: 'KYC Pending Review',
    message: '2 clients have documents awaiting KYC verification.',
    relatedType: 'Borrower',
    relatedId: 'bor-1002',
    isRead: false,
    createdAt: iso,
  },
  {
    id: 'ntf-6002',
    branchId: 'br-main',
    targetStaffId: null,
    type: 'LOAN_APPLICATION',
    title: 'New loan application',
    message: 'Application LA-2024-5567 for Ana Marie Reyes was submitted.',
    relatedType: 'Loan',
    relatedId: 'loan-2006',
    isRead: false,
    createdAt: iso,
  },
  {
    id: 'ntf-6003',
    branchId: 'br-main',
    targetStaffId: null,
    type: 'PAYMENT',
    title: 'Payment received',
    message: '₱5,000 payment received for LA-2024-3308.',
    relatedType: 'Loan',
    relatedId: 'loan-2004',
    isRead: true,
    createdAt: iso,
  },
];

export const mockAuditLogs = [
  {
    id: 'log-1',
    timestamp: iso,
    action: 'PAYMENT_RECEIVED',
    details: 'Received ₱5,000 from Liza Fernandez for LA-2024-3308. Receipt OR-2024-881235.',
    performedBy: 'Maria Santos (Loan Officer)',
    branchId: 'br-main',
    type: 'PAYMENT',
    userName: 'Maria Santos',
    userRole: 'LOAN_OFFICER',
    targetType: 'Loan',
    targetId: 'loan-2004',
    ipAddress: 'branch-portal',
  },
  {
    id: 'log-2',
    timestamp: iso,
    action: 'SAVINGS_DEPOSIT',
    details: 'Deposit of ₱2,000 to Liza Fernandez\'s savings (sav-5002).',
    performedBy: 'Maria Santos (Loan Officer)',
    branchId: 'br-main',
    type: 'SAVINGS',
    userName: 'Maria Santos',
    userRole: 'LOAN_OFFICER',
    targetType: 'SavingsAccount',
    targetId: 'sav-5002',
    ipAddress: 'branch-portal',
  },
  {
    id: 'log-3',
    timestamp: iso,
    action: 'CLIENT_REGISTERED',
    details: 'Registered new client CLI-2024-0345 (Liza Fernandez).',
    performedBy: 'Maria Santos (Loan Officer)',
    branchId: 'br-main',
    type: 'BORROWER',
    userName: 'Maria Santos',
    userRole: 'LOAN_OFFICER',
    targetType: 'Borrower',
    targetId: 'bor-1004',
    ipAddress: 'branch-portal',
  },
];

export function mockSavingsTransactions(accountId: string) {
  if (accountId === 'sav-5002') {
    return [
      { id: 'stx-1', savingsAccountId: 'sav-5002', memberId: 'bor-1004', memberName: 'Liza Fernandez', transactionNumber: 'STX-20240201-98122', date: today, type: 'Deposit', amount: 2000, balanceBefore: 20100, balanceAfter: 22100, processedBy: 'Maria Santos', notes: null, officialReceiptNumber: 'OR-20240201-98122' },
      { id: 'stx-2', savingsAccountId: 'sav-5002', memberId: 'bor-1004', memberName: 'Liza Fernandez', transactionNumber: 'STX-20240112-11803', date: '2024-01-12', type: 'Withdrawal', amount: 1500, balanceBefore: 21600, balanceAfter: 20100, processedBy: 'Maria Santos', notes: 'School materials', officialReceiptNumber: null },
    ];
  }
  return [
    { id: 'stx-3', savingsAccountId: accountId, memberId: 'bor-1001', memberName: 'Juan Dela Cruz', transactionNumber: 'STX-20240201-97213', date: today, type: 'Deposit', amount: 500, balanceBefore: 8000, balanceAfter: 8500, processedBy: 'Maria Santos', notes: null, officialReceiptNumber: 'OR-20240201-97213' },
  ];
}

export function mockReport(type: string): ReportRow {
  const summaryByType: Record<string, Record<string, any>> = {
    clients: { total: baseClients.length, active: baseClients.filter((c) => c.memberStatus === 'Active').length },
    kyc: { byStatus: baseClients.reduce<Record<string, number>>((acc, c) => { acc[c.kycStatus] = (acc[c.kycStatus] || 0) + 1; return acc; }, {}) },
    portfolio: { byStatus: baseLoans.reduce<Record<string, number>>((acc, l) => { acc[l.status] = (acc[l.status] || 0) + 1; return acc; }, {}), outstanding: baseLoans.filter((l) => ['Disbursed', 'Active', 'In Arrears'].includes(l.status)).reduce((s, l) => s + l.remainingBalance, 0) },
    overdue: { count: 1, outstanding: 26400 },
    applications: { count: baseLoans.filter((l) => ['Draft', 'Submitted', 'Under Review', 'For Assessment'].includes(l.status)).length, pending: 1 },
    collections: { total: mockTodayCollections.totals.total, count: mockTodayCollections.totals.count },
    savings: { deposits: 22600, withdrawals: 9800, totalBalances: savingsAccounts.reduce((s, a) => s + a.balance, 0) },
    groups: { count: groups.length, repaymentRate: groups[0]?.repaymentRate || 0 },
  };
  const rowsByType: Record<string, Record<string, any>[]> = {
    clients: baseClients.map((c) => ({ borrowerNumber: c.borrowerNumber, fullName: c.fullName, phone: c.phone, address: c.address, memberStatus: c.memberStatus, kycStatus: c.kycStatus, membershipDate: c.membershipDate, savingsBalance: c.savingsBalance })),
    kyc: baseClients.map((c) => ({ borrowerNumber: c.borrowerNumber, fullName: c.fullName, kycStatus: c.kycStatus, memberStatus: c.memberStatus, phone: c.phone })),
    portfolio: baseLoans.map((l) => ({ loanNumber: l.loanNumber, borrowerName: l.borrowerName, productName: l.productName, principalAmount: l.principalAmount, remainingBalance: l.remainingBalance, status: l.status, nextPaymentDate: l.nextPaymentDate, applicationDate: l.applicationDate, loanOfficerName: l.loanOfficerName })),
    overdue: baseLoans.filter((l) => l.status === 'In Arrears').map((l) => ({ loanNumber: l.loanNumber, borrowerName: l.borrowerName, remainingBalance: l.remainingBalance, daysInArrears: l.daysInArrears, nextPaymentDate: l.nextPaymentDate, loanOfficerName: l.loanOfficerName })),
    applications: baseLoans.filter((l) => ['Draft', 'Submitted', 'Under Review', 'For Assessment'].includes(l.status)).map((l) => ({ loanNumber: l.loanNumber, borrowerName: l.borrowerName, productName: l.productName, principalAmount: l.principalAmount, termMonths: l.termMonths, applicationDate: l.applicationDate, status: l.status, loanOfficerName: l.loanOfficerName })),
    collections: basePayments.map((p) => ({ receiptNumber: p.receiptNumber, loanNumber: p.loanNumber, borrowerName: p.borrowerName, amount: p.amount, paymentDate: p.paymentDate, paymentMethod: p.paymentMethod, collectedBy: p.collectedBy })),
    savings: [
      { transactionNumber: 'STX-20240201-98122', memberName: 'Liza Fernandez', type: 'Deposit', amount: 2000, balanceAfter: 22100, date: today, processedBy: 'Maria Santos' },
      { transactionNumber: 'STX-20240112-11803', memberName: 'Liza Fernandez', type: 'Withdrawal', amount: 1500, balanceAfter: 20100, date: '2024-01-12', processedBy: 'Maria Santos' },
    ],
    groups: groups.map((g) => ({ groupCode: g.groupCode, groupName: g.groupName, centerName: g.centerName, leaderName: g.leaderName, members: g.members.length, repaymentRate: g.repaymentRate, totalGroupSavings: g.totalGroupSavings, status: g.status })),
  };
  return {
    type,
    to: today,
    generatedAt: iso,
    summary: summaryByType[type] || {},
    rows: rowsByType[type] || [],
  };
}